### ISSUE TITLE
Make output files configurable

### ISSUE THREAD

**Issue by pietercolpaert** [erochest/jekyll-rdfa#7]
Right now, posts.json and posts.ttl is hard coded. As you can also create different things than posts, can we make this configurable?

Maybe it would also be interesting to have 1 file per resource instead of 1 file for all posts? Your thoughts?

**Comment by erochest** [comment]
That's been part of the plan since the beginning, but I was waiting for someone to ask. :)

I'm traveling this week, so it probably won't get done for a bit, but I'll add it to my to-do list now.

Thanks for the feature request!

**Comment by pietercolpaert** [comment]
No problem and thanks! I do not have time for doing a pull request at this time, so very happy you can take this up!

**Comment by erochest** [comment]
This is on `master`, but I'll wait to release it until I've had a chance to look at #9.

I haven't really thought yet about having a file for each resource, though. Let me think about this for a while. Out of curiosity, what is your use case for this?

**Comment by pietercolpaert** [comment]
I'm writing my PhD using jekyll, and annotate my pages with RDFa (a.o. for the citations: https://github.com/pietercolpaert/jekyll-refs). A nice to have would be to be able to query the graph and I experimented a bit with this repository for that purpose. Not entirely sure whether being able to query my PhD would be useful to anyone though...
